# Dependencies

# Permalinks
permalink:        none

# Setup
title:            Just a Coder
tagline:          'Random Stuff'
description:      'Sometimes i write to take notes, sometimes to help others.'
url:              /
baseurl:          /
timezone:         Europe/Istanbul
lsi:              true
author:
  name:           'Ahmet Huseyin Gokdayi'
  url:            https://twitter.com/ahmet_gdy

paginate:         5

# Custom vars
version:          2.1.0
gems: [jekyll-paginate, jekyll-gist]
github:
  repo:           https://github.com/daveMad

kramdown:
  input: GFM
  syntax_highlighter: rouge